# Generated by Django 3.1.7 on 2021-03-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20210323_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'darowizna', 'verbose_name_plural': 'Darowizny'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('name',), 'verbose_name': 'instytucja', 'verbose_name_plural': 'Instytucje'},
        ),
    ]
